EXE = test_m6502

CXXFLAGS = -I ../inc -I ../../inc

CXXFILES = Board.cpp test.cpp

LDFLAGS  = -L ../src -L ../../src -lboost_regex -lm6502 -leightbit

include ../../compile.mk
include ../../exe_build.mk
