LIB = liblr35902.a

CXXFLAGS = -I ../inc -I ../../inc

CXXFILES = CharacterDefinition.cpp Disassembler.cpp Display.cpp GameBoyBus.cpp IoRegisters.cpp LR35902.cpp ObjectAttribute.cpp Profiler.cpp

include ../../lib_build.mk
