LIB = liblr35902.a

CPPFLAGS = -I ../../inc

CXXFILES = CharacterDefinition.cpp Disassembler.cpp Display.cpp GameBoyBus.cpp IoRegisters.cpp LR35902.cpp ObjectAttribute.cpp Profiler.cpp

include ../../compile.mk
include ../../lib_build.mk
