EXE = test_intel8080

CXXFLAGS = -I ../inc -I ../../inc

CXXFILES = Board.cpp Configuration.cpp test.cpp

LDFLAGS  = -L ../src -L ../../src -lintel8080 -leightbit

include ../../compile.mk
include ../../exe_build.mk
