LIB = libeightbit.a

CXXFLAGS = -I ../inc

CXXFILES = BigEndianProcessor.cpp Bus.cpp Chip.cpp Device.cpp EventArgs.cpp InputOutput.cpp IntelProcessor.cpp LittleEndianProcessor.cpp Memory.cpp Processor.cpp Ram.cpp Rom.cpp UnusedMemory.cpp

include ../compile.mk
include ../lib_build.mk
