EXE = test_z80

CXXFLAGS = -I ../inc -I ../../inc

CXXFILES = Board.cpp Configuration.cpp test.cpp

LDFLAGS  = -L ../src -L ../../src -lz80 -leightbit

include ../../compile.mk
include ../../exe_build.mk
